mode:
    mode: 'train'
    multiprocessing_distributed: False
    dist_url: tcp://127.0.0.1:2345
    num_threads: 1
    do_online_eval: True
    parameter_path: './dataset/processed_data/parameter_39.pkl'
train:
    dim_x: 3
    dim_z: 3
    dim_a: 40
    num_ensemble: 32
    seed: 0
    model_name: 'tensegrity_39'
    dataset: 'tensegrity'
    input_size: 30
    data_path: './dataset/processed_data/test_dataset_39.pkl'
    batch_size: 16
    num_epochs: 100
    learning_rate: 1e-4
    weight_decay: 1e-2
    adam_eps: 1e-3
    log_freq: 50
    eval_freq: 10000
    log_directory: './experiments'
    loss: 'mse'
test:
    dim_x: 3
    dim_z: 3
    dim_a: 40
    num_ensemble: 32
    model_name: 'tensegrity_39'
    data_path: './dataset/processed_data/test_dataset_39.pkl'
    input_size: 30
    checkpoint_path: './experiments/model.pth'
    dataset: 'tensegrity'
optim:
    optim: 'adamw'
    lr_scheduler: 'polynomial_decay'